version: '3.9'

services:
  documents:
    image: postgres:16
    container_name: nextjs-db
    ports:
      - 5433:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=postgres
    restart: always
